# Generated by Django 4.2.25 on 2026-02-25 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("qa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qatask",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qa_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
