# Generated by Django 4.2.25 on 2026-05-21 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('CONFIRMED', 'Confirmed'), ('RESCHEDULED', 'Rescheduled'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=16),
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(default=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_minutes', models.PositiveIntegerField(default=30)),
                ('max_appointments_per_slot', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['doctor', 'weekday', 'start_time'],
                'indexes': [models.Index(fields=['doctor', 'weekday'], name='appointment_doctor__eb2a25_idx')],
            },
        ),
    ]
