# Generated by Django 6.0.3 on 2026-05-21 04:36

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_alter_appointment_status_doctorschedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctorschedule",
            options={"ordering": ["schedule_date", "start_time", "doctor"]},
        ),
        migrations.RemoveIndex(
            model_name="doctorschedule",
            name="appointment_doctor__eb2a25_idx",
        ),
        migrations.RemoveField(
            model_name="doctorprofile",
            name="max_appointments_per_slot",
        ),
        migrations.RemoveField(
            model_name="doctorprofile",
            name="slot_minutes",
        ),
        migrations.AddField(
            model_name="doctorschedule",
            name="schedule_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("BOOKED", "Booked"),
                    ("DONE", "Done"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="BOOKED",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="doctorschedule",
            index=models.Index(
                fields=["doctor", "schedule_date"],
                name="appointment_doctor__753316_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="doctorschedule",
            name="weekday",
        ),
    ]
