# Generated by Django 4.2.25 on 2026-03-03 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=128)),
                ("method", models.CharField(blank=True, default="", max_length=16)),
                ("path", models.CharField(blank=True, default="", max_length=512)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("ip", models.CharField(blank=True, default="", max_length=64)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("request_id", models.CharField(blank=True, default="", max_length=64)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="audit_audit_action_766c6d_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="audit_audit_user_id_a3c2bc_idx",
                    ),
                    models.Index(
                        fields=["request_id"], name="audit_audit_request_06fe30_idx"
                    ),
                ],
            },
        ),
    ]
