# Generated by Django 4.2.25 on 2026-03-25 04:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoryItem",
        ),
    ]
