# Generated by Django 4.2.25 on 2026-03-03 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scene",
                    models.CharField(
                        choices=[("translation", "Translation"), ("qa", "QA")],
                        max_length=32,
                    ),
                ),
                ("task_type", models.CharField(blank=True, default="", max_length=64)),
                ("task_id", models.CharField(blank=True, default="", max_length=64)),
                ("rating", models.SmallIntegerField()),
                ("comment", models.TextField(blank=True, default="")),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["scene", "created_at"],
                        name="feedback_fe_scene_61ca03_idx",
                    ),
                    models.Index(
                        fields=["task_type", "task_id"],
                        name="feedback_fe_task_ty_12d04e_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="feedback_fe_user_id_be0124_idx",
                    ),
                ],
            },
        ),
    ]
