# Generated by Codex on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="corrected_translation",
            field=models.TextField(blank=True, default=""),
        ),
    ]
