# Generated by Django 6.0.3 on 2026-06-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_feedback_corrected_translation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="scene",
            field=models.CharField(
                choices=[
                    ("translation", "Translation"),
                    ("qa", "QA"),
                    ("system", "System"),
                ],
                max_length=32,
            ),
        ),
    ]
