# Generated by Django 6.0.3 on 2026-07-13 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_alter_feedback_scene"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="corrected_answer",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="feedback",
            name="rating_accuracy",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="rating_clarity",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="rating_completeness",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="rating_safety",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="related_entity_keys",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="feedback",
            name="resolution",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("accepted", "Accepted — KB Updated"),
                    ("rejected", "Rejected — Not Actionable"),
                    ("deferred", "Deferred — Future Consideration"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="resolution_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="feedback",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_feedbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["resolution", "scene"], name="feedback_fe_resolut_58d29c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["scene", "rating"], name="feedback_fe_scene_3a741f_idx"
            ),
        ),
    ]
