# Generated by Django 4.2.25 on 2026-03-23 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="手机号"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "男"), ("F", "女"), ("O", "其他")],
                        default="",
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True, verbose_name="年龄")),
                (
                    "occupation",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="职业"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="科室"
                    ),
                ),
                (
                    "hospital",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="医院"
                    ),
                ),
                ("bio", models.TextField(blank=True, default="", verbose_name="个人简介")),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True, default="", max_length=500, verbose_name="头像URL"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户资料",
                "verbose_name_plural": "用户资料",
            },
        ),
    ]
