# Generated by Django 6.0.3 on 2026-04-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="age",
            field=models.IntegerField(blank=True, null=True, verbose_name="Age"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar_url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="Avatar URL"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, default="", verbose_name="Bio"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Department"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="",
                max_length=1,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="hospital",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Hospital"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="occupation",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Occupation"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Phone"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
