# Generated by Django 4.2.25 on 2026-02-24 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src_lang", models.CharField(default="en", max_length=16)),
                ("tgt_lang", models.CharField(default="zh", max_length=16)),
                ("domain", models.CharField(default="general", max_length=32)),
                ("input_text", models.TextField()),
                ("output_text", models.TextField(blank=True, default="")),
                ("terms_json", models.JSONField(blank=True, default=list)),
                ("latency_ms", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "SUCCESS"), ("FAIL", "FAIL")],
                        default="SUCCESS",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
