# Generated by Django 4.2.25 on 2026-03-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="translationtask",
            name="base_translation",
            field=models.TextField(blank=True, default="", verbose_name="Base模型翻译"),
        ),
        migrations.AddField(
            model_name="translationtask",
            name="lora_translation",
            field=models.TextField(blank=True, default="", verbose_name="LoRA模型翻译"),
        ),
        migrations.AlterField(
            model_name="translationtask",
            name="output_text",
            field=models.TextField(blank=True, default="", verbose_name="最终翻译(同LoRA)"),
        ),
    ]
