from django.urls import path
from .views import (
    KBUploadView,
    KBProcessView,
    KBListView,
    KBDashboardRedirectView,
    KBUserDashboardView,
    KBManagementDashboardView,
    TranslateKBView,
    BuildMultilangView,
    GenerateTrainingDataView,
    TermCardsView,
    KBUploadListView,
    KBUploadDetailView,
    KBEntityDetailView,
    KBCandidateListView,
    KBCandidateDetailView,
    KBCandidateApproveView,
    KBCandidateRejectView,
    KBSummaryView,
)

urlpatterns = [
    path('', KBDashboardRedirectView.as_view(), name='kb_home'),
    path('upload/', KBUploadView.as_view(), name='kb_upload'),
    path('process/<int:upload_id>/', KBProcessView.as_view(), name='kb_process'),
    path('entities/', KBListView.as_view(), name='kb_entities'),
    path('dashboard/', KBDashboardRedirectView.as_view(), name='kb_dashboard'),
    path('library/', KBUserDashboardView.as_view(), name='kb_library_dashboard'),
    path('manage/', KBManagementDashboardView.as_view(), name='kb_manage_dashboard'),
    path('translate/<int:entity_id>/', TranslateKBView.as_view(), name='kb_translate'),
    path('build_multilang/', BuildMultilangView.as_view(), name='kb_build_multilang'),
    path('generate_training_data/', GenerateTrainingDataView.as_view(), name='kb_generate_training_data'),
    path('upload_list/', KBUploadListView.as_view(), name='kb_upload_list'),
    path('summary/', KBSummaryView.as_view(), name='kb_summary'),
    path('uploads/<int:upload_id>/', KBUploadDetailView.as_view(), name='kb_upload_detail'),
    path('candidates/', KBCandidateListView.as_view(), name='kb_candidates'),
    path('candidates/<int:candidate_id>/', KBCandidateDetailView.as_view(), name='kb_candidate_detail'),
    path('candidates/<int:candidate_id>/approve/', KBCandidateApproveView.as_view(), name='kb_candidate_approve'),
    path('candidates/<int:candidate_id>/reject/', KBCandidateRejectView.as_view(), name='kb_candidate_reject'),
    path('entities/<int:entity_id>/term_cards/', TermCardsView.as_view(), name='kb_term_cards'),
    path('entities/<int:entity_id>/', KBEntityDetailView.as_view(), name='kb_entity_detail'),
]
 
